// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package osmesa.common.proto


@SerialVersionUID(0L)
final case class Countries(
    countries: _root_.scala.collection.Seq[Countries.Country] = _root_.scala.collection.Seq.empty
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[Countries] with com.trueaccord.lenses.Updatable[Countries] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      countries.foreach(countries => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(countries.serializedSize) + countries.serializedSize)
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      countries.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): Countries = {
      val __countries = (_root_.scala.collection.immutable.Vector.newBuilder[Countries.Country] ++= this.countries)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __countries += _root_.com.trueaccord.scalapb.LiteParser.readMessage(_input__, Countries.Country.defaultInstance)
          case tag => _input__.skipField(tag)
        }
      }
      Countries(
          countries = __countries.result()
      )
    }
    def clearCountries = copy(countries = _root_.scala.collection.Seq.empty)
    def addCountries(__vs: Countries.Country*): Countries = addAllCountries(__vs)
    def addAllCountries(__vs: TraversableOnce[Countries.Country]): Countries = copy(countries = countries ++ __vs)
    def withCountries(__v: _root_.scala.collection.Seq[Countries.Country]): Countries = copy(countries = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => countries
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(countries.map(_.toPMessage)(_root_.scala.collection.breakOut))
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = Countries
}

object Countries extends com.trueaccord.scalapb.GeneratedMessageCompanion[Countries] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[Countries] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): Countries = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    Countries(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[Countries.Country]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[Countries] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      Countries(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[Countries.Country]]).getOrElse(_root_.scala.collection.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = CountryProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = CountryProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = Countries.Country
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]](
    Countries.Country
  )
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = Countries(
  )
  @SerialVersionUID(0L)
  final case class Country(
      name: String = "",
      count: Int = 0
      ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[Country] with com.trueaccord.lenses.Updatable[Country] {
      @transient
      private[this] var __serializedSizeCachedValue: Int = 0
      private[this] def __computeSerializedValue(): Int = {
        var __size = 0
        if (name != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, name) }
        if (count != 0) { __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(2, count) }
        __size
      }
      final override def serializedSize: Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = name
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = count
          if (__v != 0) {
            _output__.writeInt32(2, __v)
          }
        };
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): Countries.Country = {
        var __name = this.name
        var __count = this.count
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __name = _input__.readString()
            case 16 =>
              __count = _input__.readInt32()
            case tag => _input__.skipField(tag)
          }
        }
        Countries.Country(
            name = __name,
            count = __count
        )
      }
      def withName(__v: String): Country = copy(name = __v)
      def withCount(__v: Int): Country = copy(count = __v)
      def getFieldByNumber(__fieldNumber: Int): scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = name
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = count
            if (__t != 0) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(name)
          case 2 => _root_.scalapb.descriptors.PInt(count)
        }
      }
      override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
      def companion = Countries.Country
  }
  
  object Country extends com.trueaccord.scalapb.GeneratedMessageCompanion[Countries.Country] {
    implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[Countries.Country] = this
    def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): Countries.Country = {
      require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
      val __fields = javaDescriptor.getFields
      Countries.Country(
        __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
        __fieldsMap.getOrElse(__fields.get(1), 0).asInstanceOf[Int]
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[Countries.Country] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        Countries.Country(
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[String]).getOrElse(""),
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[Int]).getOrElse(0)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Countries.javaDescriptor.getNestedTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Countries.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = Countries.Country(
    )
    implicit class CountryLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, Countries.Country]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, Countries.Country](_l) {
      def name: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.name)((c_, f_) => c_.copy(name = f_))
      def count: _root_.com.trueaccord.lenses.Lens[UpperPB, Int] = field(_.count)((c_, f_) => c_.copy(count = f_))
    }
    final val NAME_FIELD_NUMBER = 1
    final val COUNT_FIELD_NUMBER = 2
  }
  
  implicit class CountriesLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, Countries]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, Countries](_l) {
    def countries: _root_.com.trueaccord.lenses.Lens[UpperPB, _root_.scala.collection.Seq[Countries.Country]] = field(_.countries)((c_, f_) => c_.copy(countries = f_))
  }
  final val COUNTRIES_FIELD_NUMBER = 1
}
