version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk11
    commands:
      - docker -v
      - java -version
  pre_build:
    commands:
      - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
  build:
    commands:
      - mkdir -p /root/.sbt/launchers/1.3.0/
      - curl -L -o /root/.sbt/launchers/1.3.0/sbt-launch.jar https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.3.0/sbt-launch.jar
      - ls -lh /root/.sbt/launchers/1.3.0
      - ./scripts/cibuild
      - ./scripts/cipublish
artifacts:
  files:
    - osmesa-dist/**/*
