version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk11
    commands:
      - docker -v
      - java -version
  build:
    commands:
      - ls -lh
      - ./scripts/cibuild
      - ./scripts/cipublish
artifacts:
  files:
    - osmesa-dist/**/*
