version: '3'
services:
  sbt:
    image: quay.io/azavea/osmesa-sbt:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/opt/src
      - /home/vagrant/.aws:/root/.aws:ro
      - /home/vagrant/.ivy2:/root/.ivy2:rw
      - /home/vagrant/.sbt:/root/.sbt:rw
      - /home/vagrant/.m2:/root/.m2:ro
    stdin_open: true
    tty: true
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    ports:
      - 4040:4040
networks:
  default:
    external:
      name: vagrant_default
