version: '3'
services:
  geoserver:
    image: quay.io/azavea/osmesa-geoserver:latest
    build:
      context: ./services/geoserver
      dockerfile: Dockerfile
      args:
        - HADOOP_VERSION=2.7.3
        - ZOOKEEPER_VERSION=3.4.8
        - HBASE_VERSION=1.3.1
    ports:
      - 9090:9090
networks:
  default:
    external:
      name: vagrant_default
