version: '3'
services:
  hdfs-name:
    image: quay.io/azavea/osmesa-hdfs:latest
    build:
      context: ./services/hdfs
      dockerfile: Dockerfile
    command: name
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    ports:
      - 50070:50070
      - 8088:8088
  hdfs-data:
    image: quay.io/azavea/osmesa-hdfs:latest
    build:
      context: ./services/hdfs
      dockerfile: Dockerfile
    command: data
    environment:
      HADOOP_MASTER_ADDRESS: hdfs-name
    depends_on:
      - hdfs-name
  zookeeper:
    image: quay.io/azavea/osmesa-zookeeper:latest
    build:
      context: ./services/zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181
  hbase-master:
    image: quay.io/azavea/osmesa-hbase:latest
    build:
      context: ./services/hbase
      dockerfile: Dockerfile
    command: master
    ports:
      - 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    links:
      - hbase-regionserver:vagrant_hbase-regionserver_1.vagrant_default
    depends_on:
      - hdfs-name
      - hdfs-data
      - zookeeper
  hbase-regionserver:
    image: quay.io/azavea/osmesa-hbase:latest
    build:
      context: ./services/hbase
      dockerfile: Dockerfile
    command: regionserver
    ports:
      - 16030:16030
    hostname: vagrant_hbase-regionserver_1.vagrant_default
    depends_on:
      - hdfs-name
      - hdfs-data
      - zookeeper
  hbase-rest:
    image: quay.io/azavea/osmesa-hbase:latest
    build:
      context: ./services/hbase
      dockerfile: Dockerfile
    command: rest
    ports:
      - 8080:8080
      - 8085:8085
    depends_on:
      - hbase-master
      - hbase-regionserver
