---
- name: Install Docker Compose
  pip: name=docker-compose version="{{ docker_compose_version }}"

- name: Add Ansible user to Docker group
  user: name="{{ ansible_user }}"
        groups=docker
        append=yes
