sudo: required
language: bash
services:
- docker
env:
  global:
  - ORG=${TRAVIS_REPO_SLUG%/*}
  - REPO=${TRAVIS_REPO_SLUG##*-}
  - TAG=${TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}
cache:
  directories:
  - ./cache
install:
- make -e build
script:
- make -e test
before_deploy:
- docker login -p "${QUAY_PASSWORD}" -u "${QUAY_USER}" quay.io
deploy:
- provider: script
  script: make -e publish
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: make -e publish
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: VhMpkQGa7pWnxpq4yuBvXatkR4mMa/Nx/qSjv0Gd5qHy41qGKZYAqSxWivoZLRE3rgMDeL+V/I/HRmbj6nkCYD66G4uoX9peMYY/utR6K+DDOzwYFjPyS8DCekB0nBgBBIcDBGSZxz9a/HoHASGcUUTKw9pp7PZkARtSva3Rx1EreqmOBEvX7arcwjKXkS8gYjedb1Day/HW3DlRydkWCTu9s7TDHhHf6EQkzBn6p5LA71NenVTzygkhBJzV+vKz9S4AMDBJI2f7IanYlw7J4fptTUGayasKvN+SyUtWnhApozq1WdkAz6/+fWX8sTDFQDVWZvo+8Ut4EZ0qeKbTDRyjNoOT1NZkqiRAm5NIxMaDkBgXjT7tLUGgHiyydLuAJx3iXR3k2/T7KY/A85cxIPzpqt7sdtMWNB1AoCFKv0Waw0zFrbzUmwGSxukCbR74ykcW6uEnIuE7a9/6S21h4pg2Wk9J9ti4J3hEgsdqpRSriOCgaOPTaLyZrzCLCRVmxJw7goWvOj+jazfMGcNVf9BLb6aCXR02HJncAC0tO9iZSCrx4keLt56KYi9ubvPgclOuDdmoOD1T0Yfr2IhwZSSXMWfpgVO4ndFg7bmWE3FAdAFKQVLGL3K3qEHJ3gDKlSz8K0GYhpYxE0Pnwlsr21uABriJjJbtgI7N98AMl+I=
