sudo: required
language: bash
services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.8.0
  - ORG=${TRAVIS_REPO_SLUG%/*}
  - REPO=${TRAVIS_REPO_SLUG##*-}
  - TAG=${TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}
before_install:
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv -f docker-compose /usr/local/bin
install:
- make -e build
script:
- make -e test
before_deploy:
- docker login -p "${QUAY_PASSWORD}" -u "${QUAY_USER}" quay.io
deploy:
- provider: script
  script: make -e publish
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: make -e publish
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: vuctz+Zg60g/Z/apiVr+TpkbBWNKbimmgdvU8jwHT/+kNUPWCkw0v7PFghbiLgfLRg7o4YpsOqhJ2I6uNaJ0LKLGtnuqqbmzAcNSbXblzAhylOg7VxJ594qQMnBVv0W5JtzoAPakmAbOa/9NCYIObzijsLzS8IvfsES1V364mdbsDIkLqg9GshaImq+ABEJU4Q3m559eEP7wjtaxV9HyqY35/ZIcLxJJ6omwbLpZxZBQMISj1wUssTR1wKpDH+CvEh2ZVvhAZuaSFZ+RbohY3tGsYzuczczeBvqPR7ifcc7YkgTCvvSoelAQsxMefk/5PtyJHVxCC8Xi2QM6I18Agoaq7h+NaMI+wNrlxmjyAEiQO4YE3N0C4+JKroM6BgPOiIlCKcLn9x7cT4BPSCe2BwojyB7Lj5Sj7YHelCMZd1FDYZVyjb1BRgdWOvMQziiGPKC9kuB4tM8E9iMENMqi5/yqEZoKTVI4OyYaYW0ESwLrVLG/yJZKFpC4VD96mbZ119iFMgSn6ZxHrulARbWkBhMrDjurkzZxrVtZfF+sWuRdl4hDvdTW2IJxdfJDXZJhoC1CveaqcYtieuUuNhv9uxUIogVNTUM1V42fNanwEA0AtmMW/o7HedMHFMTmm68DE1JM75lpfScdzbEJEgHyW7bCrY4kvpisDBs96x7JCXI=
